### ISSUE TITLE
ICON Advice

### ISSUE THREAD

**Issue by PEPNETKing** [mypepewallet/mypepewallet#1]
Dear developer, there are some errors in the icon you are using, you may be ab
![photo_2024-12-12_13-31-16](https://github.com/user-attachments/assets/60b90d56-3886-4f4f-bd56-f1a613de9213)
le to use this

**Comment by PEPNETKing** [comment]
Sorry for some typo error

**Comment by mypepewallet** [comment]
Thank you for submitting the correct logo. The logos in the source code have been updated. Regarding the Chrome extension in the Google Web Store, since it has already been submitted for review, the logo can only be updated in the next version.
<img width="352" alt="image" src="https://github.com/user-attachments/assets/42d7c335-a82c-4e47-a2a3-1beb252b9fcf" />

**Comment by mypepewallet** [comment]
<img width="933" alt="image" src="https://github.com/user-attachments/assets/9fd20e94-d781-4c59-aa26-ddaa83eed9c6" />
